### ISSUE TITLE
Heater temperature in Aalto Readme

### ISSUE THREAD

**Issue by arinta-paavola** [MaCFP/matl-db#105]
We figured out that in the Readme document we have submitted at Aalto, the reported heater temperature values are in degrees Celsius, even though the column header in the table suggests Kelvins. Naturally, correct values would be 1007 instead of 734 in cone, and 1012 instead of 739 in gasification experiments.

@leventon are you the the person to whom this should be addressed to? Thanks!

**Comment by leventon** [comment]
Missed this one, sorry for the long delay. this is now fixed with commit [159b791](https://github.com/MaCFP/matl-db/commit/159b791aace0f2d6d347e025ba79e8ba7482fa9f)

**Comment by leventon** [comment]
Missed this one, sorry for the long delay. this is now fixed with commit [159b791](https://github.com/MaCFP/matl-db/commit/159b791aace0f2d6d347e025ba79e8ba7482fa9f)
