### ISSUE TITLE
Copper layer thickness in gasification inert test

### ISSUE THREAD

**Issue by TristanHehnen** [MaCFP/matl-db#145]
Please check the copper disc thickness in the NIST gasification apparatus description. 1/8 inch should be 3.175 mm.

**Comment by TristanHehnen** [comment]
and the according lower insulation disc

**Comment by leventon** [comment]
good catch, thank you!
Fixed with commit [06342d1](https://github.com/MaCFP/matl-db/commit/06342d1de06d5764a6c49a5957fccffcac76cbc8)

**Comment by leventon** [comment]
good catch, thank you!
Fixed with commit [06342d1](https://github.com/MaCFP/matl-db/commit/06342d1de06d5764a6c49a5957fccffcac76cbc8)
