### ISSUE TITLE
Note on Aalto Data Set in TIFP Data Set

### ISSUE THREAD

**Issue by TristanHehnen** [MaCFP/matl-db#94]
In the [README file of TIFP](https://github.com/MaCFP/matl-db/tree/master/Non-charring/PMMA/TIFP), at the end of the Cone Calorimeter section, there is a note about the adjusted Aalto data as is in the respective file from Aalto. 

Could you please check if this is just a copy-paste-error or if there is more to it, e.g. if the TIFP data was adjusted as well or if other entries are subject of a copy-paste-error in this section?

Thanks,
Tristan

**Comment by leventon** [comment]
The adjustment was made to that dataset and so that extra text belongs in the README, I removed the copy/paste error regarding the institution name.

Good catch, Tristan

**Comment by TristanHehnen** [comment]
Great, thank you very much!
